import anndata as ad
import scanpy as sc
import hdf5plugin
from scipy import sparse
import pandas as pd

def steadystate_to_adata(path_to_data : str):
    """
    Takes a .parquet file containing the steady states generated by GRiNS-Racipe and turns it into an AnnData object.
    Do note that the steady state entries in grins_data.X are not discrete. 

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the GRiNS steady state solutions.
    """

    print(f"Read {path_to_data}.parquet...",end="\t")
    sol_df = pd.read_parquet(f"{path_to_data}.parquet")
    
    # Create the AnnData object:
    print("Create AnnData object...",end="\t")
    gk_cols = [col for col in sol_df.columns if "gk_" in col]
    gene_cols = [col.replace("gk_", "") for col in sol_df.columns if "gk_" in col]
    sol_sparse = sparse.csr_matrix(sol_df.loc[:,gene_cols].values)
    grins_data = ad.AnnData(sol_sparse)
    grins_data.obs_names = [str(sol_df.loc[:,"param_index"][i])+"_"+str(sol_df.loc[:,"ic_index"][i]) for i in range(sol_df.shape[0])]
    grins_data.var_names = gene_cols



def discrete_to_adata(path_to_data : str, is_racipe : bool):
    """
    Takes the state counts saved in a .csv file and turns them into an Anndata object.
    Do note that the on/off states in grins_data.X should not be regarded as counts whatsoever.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    is_racipe : bool
        A boolean to indicate whether or not the data is generated through Racipe (True) or Ising (False).

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the discrete states of GRiNS.
    """
    pass


def normalize_adata(grins_data):
    """
    Takes the AnnData object just created and normalized it, following the normalization pipeline from the software project.
    """
    # Calculate QC metrics:
    print("Calculate QC metrics...",end="\t")
    sc.pp.calculate_qc_metrics(grins_data,percent_top=[20],inplace=True)

    # Log-normalize the layers:
    print("Normalize Data...",end="\t")
    grins_data.layers["normalized"] = grins_data.X.copy()
    sc.pp.normalize_total(grins_data, target_sum=None,layer="normalized")
    grins_data.layers["log1p"] = grins_data.layers["normalized"].copy()
    sc.pp.log1p(grins_data, layer="log1p")

    # Search for highly variable genes:
    print("Find highly variable genes...",end="\t")
    sc.pp.highly_variable_genes(grins_data,n_top_genes=5000, subset=True,layer="log1p")

    return grins_data


def grins_to_adata(path_to_data : str, is_racipe : bool, is_discrete : bool = True):
    """
    Turns either the steady states generated by Racipe or the discrete on/off states generated by Racipe or Ising and turns them into an Anndata object.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    is_racipe : bool
        A boolean indicating whether or not the data is generated through Racipe (True) or Ising (False).
    is_discrete : bool
        A boolean indicating whether the steady states 

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the discrete states of GRiNS.

    Examples:
    ---------
    racipe_data = grins_to_adata(path_to_data, is_racipe = True, is_discrete = False)
    ising_data = grins_to_adata(path_to_data, is_racipe = False)
    """

    # Generate AnnData object:
    if is_discrete:
        grins_data = discrete_to_adata(path_to_data, is_racipe) 
    else:
        if not is_racipe:
            raise Exception("Ising does not generate any steady states. Therefore, is_discrete = False and is_racipe = False are not compatible.")
        grins_data = steadystate_to_adata(path_to_data)

    # Normalize:
    grins_data = normalize_adata(grins_data)    

    # Save the object:
    print(f"Save the AnnData object to {path_to_data}.h5ad...", end="\t")
    ad.settings.allow_write_nullable_strings = True # <- remove later
    grins_data.write_h5ad(
        f"{path_to_data}.h5ad", # maybe change path later
        compression=hdf5plugin.FILTERS["zstd"]
    )

    return grins_data


def save_full_adata():
    # Takes the adata object from control and perturb cells as input, concatenates them, and saves them as full h5ad file
    pass

def missingness_filter():
    # If control data is available: maybe use something like scImpute (https://pmc.ncbi.nlm.nih.gov/articles/PMC12908672/) to find probability of a zero being a dropout
    # Then calculate for each gene the percentage of dropouts and use that to create dropouts in synth data

    # Otherwise, maybe do the same but average over literature data? if that exists?
    pass

def get_dist_matrix():
    pass

def calc_clusters():
    # Silhouette Score
    pass

def reduce_param_ranges():
    # Get param ranges of best cluster as .csv
    pass

def set_param_ranges():
    pass